services:
  webdna-server:
    build:
      context: ..
      dockerfile: build/docker/Dockerfile
    container_name: webdna-server-dev
    command: ["/usr/local/bin/start-webdna.sh"]
    ports:
      - "8080:80"  # Direct access for development
    volumes:
      - ../html:/var/www/html:rw
      - ../logs:/var/log/apache2:rw
      - ../WebCatalogEngine:/usr/lib/cgi-bin/WebCatalogEngine:rw
    env_file:
      - .env.dev
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
      - APACHE_LOG_DIR=/var/log/apache2
      - HOST_UID=1000
      - HOST_GID=1000
      - ENVIRONMENT=development
      - BASE_URL=http://localhost:8080
    depends_on:
      - postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/WebCatalog"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - webdna-network

  postgres:
    image: postgres:15-alpine
    container_name: webdna-postgres-dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../config/postgres:/docker-entrypoint-initdb.d:ro
    env_file:
      - .env.dev
    environment:
      - POSTGRES_DB=webdna_dev
      - POSTGRES_INITDB_ARGS=--encoding=UTF8 --locale=C
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U webdna_dev_user -d webdna_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - webdna-network

  # Nginx disabled for development - direct access to webdna-server

volumes:
  postgres_data:

networks:
  webdna-network:
    driver: bridge