name: Development Deployment

on:
  push:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: self-hosted
    steps:
      - name: Clean workspace
        run: |
          # Fix permissions on any files that might be owned by containers
          sudo chown -R $USER:$USER . || true
          # Clean up any existing containers
          docker system prune -f || true
      
      - uses: actions/checkout@v4
      
      - name: Validate Docker files
        run: |
          # Check if Dockerfile exists and is valid
          if [ -f "build/docker/Dockerfile" ]; then
            echo "✓ Dockerfile found"
            # Basic syntax check
            docker run --rm -i hadolint/hadolint < build/docker/Dockerfile || echo "Dockerfile has warnings"
          else
            echo "✗ Dockerfile not found"
            exit 1
          fi
      
      - name: Validate Docker Compose files
        run: |
          # Check if docker-compose files exist
          if [ -f "deploy/docker-compose.yml" ]; then
            echo "✓ docker-compose.yml found"
            # Validate compose file syntax
            docker compose -f deploy/docker-compose.yml config > /dev/null
          else
            echo "✗ docker-compose.yml not found"
            exit 1
          fi
      
      - name: Check test scripts
        run: |
          chmod +x ./tests/*.sh
          echo "✓ Test scripts are executable"
          # Syntax check for shell scripts
          for script in ./tests/*.sh; do
            bash -n "$script" && echo "✓ $script syntax OK"
          done

  deploy:
    name: Deploy to Development
    runs-on: self-hosted
    needs: test
    
    steps:
      - name: Clean workspace
        run: |
          # Fix permissions on any files that might be owned by containers
          sudo chown -R $USER:$USER . || true
      
      - uses: actions/checkout@v4
      
      - name: Deploy to Development
        run: |
          echo "🚀 Starting development deployment..."
          
          # Navigate to deploy directory
          cd deploy
          
          # Stop existing containers
          docker compose down || true
          
          # Build fresh images
          docker compose build --no-cache
          
          # Start development environment
          docker compose up -d
          
          # Wait for services to be ready
          echo "Waiting for services to start..."
          sleep 30
          
          # Check service health
          docker compose ps
          
          echo "✅ Development deployment completed"